collections:

  - name: ansible.controller
    version: 4.6.16
    source: https://aap.apps.hub.aws.tntinfra.net/pulp_ansible/galaxy/rh-certified/

  - name: ansible.platform
    version: 2.5.20250702
    source: https://aap.apps.hub.aws.tntinfra.net/pulp_ansible/galaxy/rh-certified/

  - name: ansible.hub
    version: 1.0.0
    source: https://aap.apps.hub.aws.tntinfra.net/pulp_ansible/galaxy/rh-certified/

  - name: ansible.eda
    version: 2.8.2
    source: https://aap.apps.hub.aws.tntinfra.net/pulp_ansible/galaxy/rh-certified/

  - name: infra.aap_configuration
    version: 3.8.2
    source: https://aap.apps.hub.aws.tntinfra.net/pulp_ansible/galaxy/validated/

  - name: infra.aap_utilities
    version: 2.8.0
    source: https://aap.apps.hub.aws.tntinfra.net/pulp_ansible/galaxy/validated/
